services:
  backend:
    build: .
    ports:
      - "80:80"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_proyectoIntegrador?useSSL=false
      SPRING_DATASOURCE_USERNAME: java_user
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_proyectoIntegrador
      POSTGRES_USER: java_user
      POSTGRES_PASSWORD: 0000
